### ISSUE TITLE
trace: 'attempt to add with overflow'

### ISSUE THREAD

**Issue by dergoegge** [awslabs/snapchange#4]
I always get the following error when trying to use the trace feature:
```
$ RUST_BACKTRACE=1 cargo +nightly run -- trace snapshot/crashes/SIGSEGV_addr_0xcafecafe_code_AddressNotMappedToObject/c2b9b72428f4059c
...
[2023-06-02T08:59:17Z INFO  snapchange::stack_unwinder] "./snapshot/vmlinux" has no .eh_frame_hdr
[2023-06-02T08:59:17Z INFO  snapchange::cmdline] Gathering unwinders took: 139.963µs
[2023-06-02T08:59:17Z INFO  snapchange::commands::trace] Gathering single step trace of "snapshot/crashes/SIGSEGV_addr_0xcafecafe_code_AddressNotMappedToObject/c2b9b72428f4059c"
[2023-06-02T08:59:17Z INFO  snapchange::commands::trace] Fuzzer: 0x5555555552f8 RIP: 0x5555555552f8
[2023-06-02T08:59:18Z INFO  snapchange::commands::trace] Single step trace
[2023-06-02T08:59:18Z INFO  snapchange::commands::trace] Tracing timeout: 60s
[2023-06-02T08:59:18Z INFO  snapchange::commands::trace] Getting vmlinux
[2023-06-02T08:59:19Z INFO  snapchange::commands::trace] Getting binary contexts
thread 'main' panicked at 'attempt to add with overflow', /root/snapchange/src/addrs.rs:74:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5ea3f0ae08c07472239a94ce55601e9b63eb1f45/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/5ea3f0ae08c07472239a94ce55601e9b63eb1f45/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/5ea3f0ae08c07472239a94ce55601e9b63eb1f45/library/core/src/panicking.rs:117:5
   3: snapchange::addrs::VirtAddr::offset
             at /root/snapchange/src/addrs.rs:74:18
   4: snapchange::memory::Memory::set_page_boundaries
             at /root/snapchange/src/memory.rs:1042:21
   5: snapchange::memory::Memory::read_bytes
             at /root/snapchange/src/memory.rs:642:9
   6: snapchange::memory::Memory::read_c_string
             at /root/snapchange/src/memory.rs:1166:13
   7: snapchange::fuzzvm::FuzzVm<FUZZER>::read_c_string
             at /root/snapchange/src/fuzzvm.rs:2773:9
   8: snapchange::commands::trace::start_core
             at /root/snapchange/src/commands/trace.rs:306:33
...
```

I have been able to work around the issue with the following patch but I'm guessing that this more or less just ignores the error instead of addressing the actual issue:
```diff
diff --git a/src/addrs.rs b/src/addrs.rs
index 6752033..771f176 100644
--- a/src/addrs.rs
+++ b/src/addrs.rs
@@ -71,7 +71,10 @@ impl VirtAddr {
     #[allow(dead_code)]
     #[must_use]
     pub const fn offset(self, offset: u64) -> VirtAddr {
-        VirtAddr(self.0 + offset)
+        match self.0.checked_add(offset) {
+            None => self,
+            Some(addr) => VirtAddr(addr),
+        }
     }

     /// Get the 4 page table indexes that this [`VirtAddr`] corresponds maps with when
```

**Comment by corydu** [comment]
Oh nice! Be sure to run the fuzzer with `cargo run --release`. We might want a `try_offset` in the future to not silently handling the wrapping addition.
